name: valgrind

on:
  push
jobs:
  memory_leak_test:
    runs-on: ubuntu-latest
    container: richardvas/mosze:latest
    steps:
        - uses: actions/checkout@v2
        - name: Set permission
          run: chmod a+x ./valgrind.sh
        - name: build
          run: g++ -Wall -g -o a.out *.cpp
        - name: Checking memory leak
          run: ./valgrind.sh
